BaseURL = "http://www.pitslamp.com"
languageCode = "en-us"
title = "PitsLamp Photography"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = false
paginate = 10
paginatePath = "page"
pluralizeListTitles = true
rssURI = "feed"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  logo = "/images/logo_pitslamp.png"
  description = "Full service photography"
  email = "info@pitslamp.com"
  shortDescription = ""
  author = "Filip Bunkens"
  SidebarRecentLimit = 5
  AnalyticsID = "UA-2550570-12"

[[menu.main]]
    name = "Home"
    pre = ""
    weight = -110
    identifier = "Home"
    url = "/"
[[menu.main]]
	name="Blog"
	pre= ""
	weigth = 0
	identifier = "blog"
	url = "/blog/"

